### ISSUE TITLE
有问题可以在这里反应

### ISSUE THREAD

**Issue by Zy143L** [Zy143L/qinglong#1]
#有问题可以在这里反应 只处理2.2的问题

**Comment by yanyuwangluo** [comment]
机器人正常用吗

**Comment by Zy143L** [comment]
> 机器人正常用吗

正常

**Comment by zayn-0101** [comment]
在甲骨文 VPS 上安装，添加 cookie 时点确定，确定键会一直转圈，不会成功，刷新后查看页面也是空白，但查看 cookie.sh 和 cookie.db，其实都是有内容的，尝试跑过一次脚本也正常，可以正常识别 cookie。
不删除映射出的文件夹，删除原来容器重新创建的话，Session 管理页面也是显示空白的 🥲
也试过删除过文件夹，重新拉取镜像创建容器多次，都是一样的情况。

对了，这个情况在 N1 盒子上没有出现，目前添加 cookie 的操作和显示一切正常。

**Comment by Zy143L** [comment]
> 在甲骨文 VPS 上安装，添加 cookie 时点确定，确定键会一直转圈，不会成功，刷新后查看页面也是空白，但查看 cookie.sh 和 cookie.db，其实都是有内容的，尝试跑过一次脚本也正常，可以正常识别 cookie。
> 不删除映射出的文件夹，删除原来容器重新创建的话，Session 管理页面也是显示空白的 🥲
> 也试过删除过文件夹，重新拉取镜像创建容器多次，都是一样的情况。
> 
> 对了，这个情况在 N1 盒子上没有出现，目前添加 cookie 的操作和显示一切正常。

你可以强制刷新看一下..如果cookiedb都正常的话 那就可能是前端的遗留bug吧

**Comment by zayn-0101** [comment]
> > 在甲骨文 VPS 上安装，添加 cookie 时点确定，确定键会一直转圈，不会成功，刷新后查看页面也是空白，但查看 cookie.sh 和 cookie.db，其实都是有内容的，尝试跑过一次脚本也正常，可以正常识别 cookie。
> > 不删除映射出的文件夹，删除原来容器重新创建的话，Session 管理页面也是显示空白的 🥲
> > 也试过删除过文件夹，重新拉取镜像创建容器多次，都是一样的情况。
> > 对了，这个情况在 N1 盒子上没有出现，目前添加 cookie 的操作和显示一切正常。
> 
> 你可以强制刷新看一下..如果cookiedb都正常的话 那就可能是前端的遗留bug吧

也试过 🥲 看来要放弃在 VPS 上使用的想法了

**Comment by MangoDong** [comment]
我cookie 超过43 cookie界面救不显示了  然后看了一下目录下面 cookie.list 是正常的 问 是BUG 吗？
![image](https://user-images.githubusercontent.com/36813488/123515377-b8ac4400-d6c9-11eb-8c32-3fb1ed83b27b.png)

**Comment by Zy143L** [comment]
> 我cookie 超过43 cookie界面救不显示了 然后看了一下目录下面 cookie.list 是正常的 问 是BUG 吗？

cookie多了这个要加载很久...因为会去京东查询cookie状态 号多的建议分面板跑 或者升级到2.8 就不会卡了

**Comment by MangoDong** [comment]
> > 我cookie 超过43 cookie界面救不显示了 然后看了一下目录下面 cookie.list 是正常的 问 是BUG 吗？
> 
> cookie多了这个要加载很久...因为会去京东查询cookie状态 号多的建议分面板跑 或者升级到2.8 就不会卡了

可否加入并发查询呢？

**Comment by Zy143L** [comment]
> > > 我cookie 超过43 cookie界面救不显示了 然后看了一下目录下面 cookie.list 是正常的 问 是BUG 吗？
> > 
> > 
> > cookie多了这个要加载很久...因为会去京东查询cookie状态 号多的建议分面板跑 或者升级到2.8 就不会卡了
> 
> 可否加入并发查询呢？

我不负责青龙2.2的后续维护 只是做一个备份罢了

**Comment by MangoDong** [comment]
> > > > 我cookie 超过43 cookie界面救不显示了 然后看了一下目录下面 cookie.list 是正常的 问 是BUG 吗？
> > > 
> > > 
> > > cookie多了这个要加载很久...因为会去京东查询cookie状态 号多的建议分面板跑 或者升级到2.8 就不会卡了
> > 
> > 
> > 可否加入并发查询呢？
> 
> 我不负责青龙2.2的后续维护 只是做一个备份罢了

好的 ，感谢您的回复。

**Comment by ghost** [comment]
新版的JDC，AMD64的，执行./JDC提示net found x86平台，

**Comment by huaxxx** [comment]
京东到家果园
❌失败! 原因:TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]!
这是什么问题呢 要是Cookie 的话 青龙我也没改动过

**Comment by huaxxx** [comment]
京东到家果园
❌失败! 原因:TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["Cookie"]!
这是什么问题呢 要是Cookie 的话 青龙我也没改动过

**Comment by ghost** [comment]
我更新了还是提示not found，用的jdcamd64   我是X86平台的openwrt的docker

**Comment by Zy143L** [comment]
> 我更新了还是提示not found，用的jdcamd64 我是X86平台的openwrt的docker

看新的releases 并注意检测权限问题

**Comment by ghost** [comment]
> > 我更新了还是提示not found，用的jdcamd64 我是X86平台的openwrt的docker
> 
> 看新的releases 并注意检测权限问题

谢谢大佬，已经可以了

**Comment by ghost** [comment]
> > 我更新了还是提示not found，用的jdcamd64 我是X86平台的openwrt的docker
> 
> 看新的releases 并注意检测权限问题

大佬JDC_AMD64可以安装，但是设置好了以后，扫码就提示连接服务器失败，我问了好几个人用这个有这种问题

**Comment by l8higher** [comment]
大佬有想法修复泄露ck的bug吗？
