### ISSUE TITLE
推送消息模板比原版漂亮，怎么改原版

### ISSUE THREAD

**Issue by hdstar2009** [Zy143L/qinglong#2]
腾讯云服务器上和家里装的分别了原版2.2和这里的2.2，发现这里的2.2版的推送消息更美观和便捷，想问下要如何更改或者说替换掉原版那些文件才能实现这样的效果？

**Comment by Zy143L** [comment]
消息推送我没动啊..怎么说更好看?

**Comment by hdstar2009** [comment]
明白了。是pushplus的问题，他推送到消息样式会变，现在变小程序了。
