### ISSUE TITLE
脚本感觉不会自己关闭

### ISSUE THREAD

**Issue by CN-YoungYang** [Zy143L/qinglong#7]
![image](https://user-images.githubusercontent.com/25340441/124052245-a5460380-da50-11eb-82a3-cba3605cfc0f.png)

![image](https://user-images.githubusercontent.com/25340441/124052262-ac6d1180-da50-11eb-9375-8609480d6ae8.png)

![image](https://user-images.githubusercontent.com/25340441/124052269-af680200-da50-11eb-8299-e66c1d9ba685.png)

日志里面 显示 都结束了，但是 面板里面 还是显示 进行中。

**Comment by l8higher** [comment]
那个跟大佬没啥关系，原版也有这个无伤大雅的问题，自己手动关一下不就好了。

**Comment by Zy143L** [comment]
青龙祖传bug...等后续看2.8 whyour大佬怎么处理 我看能同步过来就尽量
